### ISSUE TITLE
[FEAT] Switch TV On (WOL)?

### ISSUE THREAD

**Issue by popy2k14** [eslavnov/pylips#16]
First, thanks for this beautiful python script!
Back half a year i was struggling to control my new "65PUS8102" (android tv) from windows and eventghost. This was solved by an modified older philips script which was no so mighty as this :-)
Currently did'nt tried it, but it looks very promissing and i will try it soon.

So here is my question/feature request:
Back half a year i have solved it with an usb -> ir transmitter and sent "on" (or 1) to switch it on.
I realized that the JS api to turn it on does'nt work when the tv was off for an amount off time.
WOL did'nt work, regardless of its power state.
I'll think it enters some sort of deep standby and switches off network.
Yeah, there is an option to deactivate it, but sadly this has'nt solved the issue.
I could not power it on over network.

I have read your very detailed readme (thanks for this) but could not find any word of this "issue" i had. In the meantime i have received the Pie update but did not tried JS or WOL again.

**How do you power on the philips android tv over network without the use of the philips app?**
**Does WOL work for you, all the time?
Which settings do i have to change that it maybe work?
Any chance to get a WOL feature, or is it already implemented?**

Thank a lot and keep up the good work

**Comment by eslavnov** [comment]
Hi! Thank you for your kind words!

I was actually waiting for somebody to bring up WoL support sooner or later... I've struggled A LOT with trying to turn the TV on:
1) The API indeed stops responding after the TV has been off for some time. I've also tried various deep sleep/eco options in the TV, but still no luck.
2) HDMI-CEC works with something like a Raspberry Pi, but I've had mixed experience with it: when it works - it works, but sometimes it just failed on me. Could be a problem with my RPi, though - I didn't troubleshoot it much.
3) WoL sorta works, but it sucks. If I remember correctly, I had to enable WoL option somewhere in the network settings of the TV, then you send a magic packet with the TV's MAC address and it works for me (at least on Oreo, haven't tested it on Pie). But the problem is that it's quite unreliable (sometimes one packet does the job, but sometimes I need to send several) and the whole process takes a rather long time to work (sometimes up to 20-30 seconds). Not sure why Philips TVs behave this way (WoL works perfectly with my other tech)... 
4) Your best choice is indeed an ir transmitter, I am using Broadlink rm mini 3 which works on Wi-Fi and it's the best $15 I've ever spent. I use Pylips (in MQTT mode) to monitor the current state of the TV and to turn it OFF with the API, while using Broadlink to turn it ON. Works great!

So, the lack of WoL support in Pylips is a design choice of mine: it's super-easy to implement, but it's impossible to guarantee a reasonable performance with Philips TVs (at least in my experience). I'd rather have no functionality than a broken one, so no plans to implement it...

**Comment by popy2k14** [comment]
Thank you @eslavnov to get in touch with me regarding this feature request.

I now have done several tests with WoWLAN + JS API and got an reliable way to wake my 65PUS8102!
Have tested this just on CLI and wrote an bash script which should do the job in all power states of the tv. 

My Setup and needed settings:
- my tv has two network connections (wired & wifi) with different IP's (sure :-) )
- WoWLAN must be enabled on the tv's network settings and the philips app should wake the tv in any power state (also when it is more than ~15 minutes in standby)
- deep standby must be disabled in energy options (can't spell it correctly in english because i have set my TV to german)

To wake it from standby when wired network interface is shutdown, do the following:
- send the magic packet to the wired interface (i'll send it three times, just to be sure. Did'nt tested with the WIfi mac)
- now the WIFI interface gets online for ~30 secs (ICMP/ping is reachable) and waiting for JS API request
- send Digit1 key to finally wake the TV

My script takes care if the wired interface is online (tv is on, or ~15minutes in standby and not disabled the wired interface). If so, It just sends the Digit1 api key command to the wired IP instead of the wifi ip, when in deep standby as described above.

Must test the script in the coming days and than i can provide it.

Can you test this on your set and maybe we finally get an reliable way of waking those tv sets from standby  and get rid of any IR transmitter (and maybe added to pylips? :-) ).

Keep up the good work
pOpY

**Comment by popy2k14** [comment]
Sadly, it does'nt work reliable. It looked good at first tries, but now i am back with my good old IR blaster :-)

**Comment by Mic-M** [comment]
Great discussion. Just sharing my solution/workaround:
I am using a Denon receiver, which is connected via HDMI with the Philips TV. My environment is [ioBroker](https://github.com/ioBroker/ioBroker) as smart home basis, and it has a plugin (they call plugins "adapters") to control the Denon receiver, [link](https://github.com/foxriver76/ioBroker.denon). 
Implementation:
If you enter the setup menu of the Denon receiver, the TV will turn on thru HDMI. So I've written a JavaScript within ioBroker which does the rest: once I click on my smart phone or tablet on "TV on" button, or if I tell Alexa that I want to watch TV, it will turn on the TV through the Denon, and the Javascript will then change the TV screen to Netflix, for example.

**Comment by eslavnov** [comment]
Thanks, I actually own a denon receiver as well so I might give it a try someday!

**Comment by popy2k14** [comment]
@Mic-M thx for this "great" solution/workaround.
That sound so simple :-)
I also own a Denon receiver and will test it.
