### ISSUE TITLE
[FEAT] Screen off but keep audio

### ISSUE THREAD

**Issue by Flavien06** [eslavnov/pylips#23]
On my philips I have an option to turn off the screen but keep the sound. 
Used with audio applications like chromecast or spotify ...
Can this command be added? I did not find it in the api joint sapce: '(

**Comment by eslavnov** [comment]
Hey, there is indeed such an option, it is controlled by Nodeid 2131230820:
```
python pylips.py --command post --path 'menuitems/settings/current' --body '{"nodes":[{"nodeid":2131230820}]}'

{"values":[{"value":{"Nodeid":2131230820,"Controllable":true,"Available":true,"string_id":"Screen Off"}}],"version":0}
```

The problem is that this node is missing the "data" key which is usually a True/False toggle that you can change. Since this key is missing and the mobile app also does not have this functionality, I haven't yet found a way to control it. So I would not count on it - at least I am out of ideas...

**Comment by FezVrasta** [comment]
@eslavnov this feature can only be turned on, to turn the screen back on you are only supposed to press any button on the remote.

Do you think that may be the reason why the node doesn't accept On/Off?
