### ISSUE TITLE
is there a java version for this project & emulator question?

### ISSUE THREAD

**Issue by theRemoter** [eslavnov/pylips#87]
Hello

thanks for this great lib!
1. is there a java version for this project?
2. is there a way to test this project on some kind of emulator if i don't have a philips tv?

**Comment by eslavnov** [comment]
Hi there,

1. There is no Java version. I'm struggling to imagine a use case for that, why do you ask?
2. Not sure that I get the question. What's the point if you don't have an Philips tv?

**Comment by theRemoter** [comment]
Hi.
1. just for a practicing study, I thought it would be educative to create a java version of it
2. I'll clarify myself- was wondering if there are like unit tests or dummy api responses for testing if a philips tv isn't always available.

**Comment by eslavnov** [comment]
No, there are no unit tests. You can see examples of the responses in the wiki.

Looking at your issues in other repos, I'd go on a limb and assume that you want to build some kind of a universal remote app in Java, right? I'd recommend thinking about integrating existing projects as opposed to re-implementing them in Java - otherwise it will be a nightmare to maintain, especially if you don't have all those TVs. 

Closing this issue since it does not really relate to Pylips functionality.
